#!/bin/bash

# Retrieve arguments
domain=$1
path=$2

app_name="openphoto"

# Check domain/path availability
sudo yunohost app checkurl $domain$path -a $app_name
if [[ ! $? -eq 0 ]]; then
    exit 1
fi

# Generate random password
db_pwd=$(dd if=/dev/urandom bs=1 count=200 2> /dev/null | tr -c -d 'A-Za-z0-9' | sed -n 's/\(.\{24\}\).*/\1/p')

# Use '$app_name' as database name and user
db_user=$app_name

# Initialize database and store mysql password for upgrade
sudo yunohost app initdb -p $db_pwd $db_user
sudo yunohost app setting $app_name mysqlpwd -v $db_pwd

# Install needed packages
sudo apt-get install -y php5-fpm curl php5-curl php5-gd php5-mcrypt php-pear
# Optionnal dependencies
sudo apt-get install -y php5-dev php5-imagick exiftran
sudo pecl install oauth
sudo bash -c 'echo "extension=oauth.so" >> /etc/php5/conf.d/oauth.ini'

# Copy files to the right place
final_path=/var/www/$app_name
sudo mkdir -p $final_path
git clone git://github.com/photo/frontend.git /tmp/openphoto
sudo mv -- /tmp/openphoto/src/* $final_path/
sudo rm -rf -- /tmp/openphoto/

# Set permissions to $app_name directory
sudo useradd $app_name -d $final_path
sudo mkdir -p -- $final_path/logs
sudo chown -R -- $app_name:www-data $final_path

# Modify Nginx configuration file and copy it to Nginx conf directory
sed -i "s@PATHTOCHANGE@$path@g" ../conf/nginx.conf
sed -i "s@ALIASTOCHANGE@$final_path/@g" ../conf/nginx.conf
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/$app_name.conf

sed -i "s@NAMETOCHANGE@$app_name@g" ../conf/php-fpm.conf
finalphpconf=/etc/php5/fpm/pool.d/$app_name.conf
sudo cp ../conf/php-fpm.conf $finalphpconf
sudo chown root: $finalphpconf
sudo chmod 644 $finalphpconf

finalphpini=/etc/php5/fpm/conf.d/20-$app_name.ini
sudo cp ../conf/php-fpm.ini $finalphpini
sudo chown root: $finalphpini
sudo chmod 644 $finalphpini

# Reload Nginx and regenerate SSOwat conf
sudo service php5-fpm restart
sudo service nginx reload
sudo yunohost app ssowatconf
