#!/bin/bash

app_name="openphoto"

# Retrieve arguments
domain=$(sudo yunohost app setting $app_name domain)
path=$(sudo yunohost app setting $app_name path)
#user=$(sudo yunohost app setting $app_name admin_user)
db_pwd=$(sudo yunohost app setting $app_name mysqlpwd)

# Remove trailing "/" for next commands
path=${path%/}

# Use '$app_name' as database name and user
db_user=$app_name

# Upate needed packages
sudo apt-get install -y php5-fpm curl php5-curl php5-gd php5-mcrypt php-pear
# Optionnal dependancies
sudo apt-get install -y php5-dev php5-imagick exiftran
sudo pecl install -y oauth
sudo echo "extension=oauth.so" >> /etc/php5/conf.d/oauth.ini

# Copy files to the right place
final_path=/var/www/$app_name
sudo mkdir -p $final_path
sudo cp -a ../sources/* $final_path
sudo cp ../conf/nginx.conf   /etc/nginx/conf.d/$domain.d/$app_name.conf
sudo cp ../conf/php-fpm.conf /etc/php5/fpm/pool.d/$app_name.conf
sudo cp ../conf/php-fpm.ini  /etc/php5/fpm/conf.d/20-$app_name.ini
sudo chown -hR $app_name:www-data $final_path
sudo chmod -R 644 $final_path

# Change variables in $app_name configuration
sudo sed -i "s@PATHTOCHANGE@$path@g"         /etc/nginx/conf.d/$domain.d/$app_name.conf
sudo sed -i "s@ALIASTOCHANGE@$final_path/@g" /etc/nginx/conf.d/$domain.d/$app_name.conf
sudo sed -i "s@NAMETOCHANGE@$app_name@g"     /etc/nginx/conf.d/$domain.d/$app_name.conf
sudo sed -i "s@NAMETOCHANGE@$app_name@g"     /etc/php5/fpm/pool.d/$app_name.conf

# Reload Nginx and regenerate SSOwat conf
sudo service php5-fpm restart
sudo service nginx reload
sudo yunohost app setting $app_name skipped_uris -v "/"
sudo yunohost app ssowatconf
